### ISSUE TITLE
Pyclone Input

### ISSUE THREAD

**Issue by mkinnaman** [mcmero/SVclone#10]
Hi Team,

I was thinking about how to call clusters across multiple samples and wanted to get your thoughts on using the ccube_sv_input file that is generated and converting it to a pyclone input. I was thinking you could average the reads/depth over the two breakpoints but not sure how to approach sv's with different copy number calls at the two breakpoints. Could limit analysis to SV's which have the same CN calls but would lose a lot of SVs that way.

I appreciate your thoughts.

Thanks,
Michael

**Comment by mcmero** [comment]
Hi Michael,

Although there's no ideal solution I can think of, here's are a few options you can try:

- Take one side of the SVs only -- you could run this twice using the left and right sides and check the discrepancy in the downstream results.
- Average the normal read counts and keep only CN states that are the same (as you suggest). This might let you identify the clusters if you have enough SVs, and you could then run SVclone's clustering to check the CCFs/clusters of the SVs you missed.
- Run SVclone's clustering separately for each sample, then match the SV CCFs between samples. While it would be tricky to get consensus clusters, you will likely be able to tell (roughly) how similar the clonal structure is between samples. 

Whichever option works the best will likely depend on your individual data set and experiment. 

Cheers,
Marek

**Comment by mkinnaman** [comment]
Thanks for the insight - very helpful!
