### ISSUE TITLE
VCF input formats

### ISSUE THREAD

**Issue by willhooper** [mcmero/SVclone#11]
Hi, 

I'm having some some trouble getting my VCFs to work with the filter step, and was wondering what the specific requirements were for each `--snv_format` option (`sanger, mutect, mutect_callstats, consensus, multisnv`). My raw mutect calls work fine with the `mutect` option, however I'd prefer to use my downstream calls that include additional callers and filters. 

My apologies if this is already documented somewhere. 

Thanks!
Will

**Comment by mcmero** [comment]
Hi Will,

I've added some more information on the SNV VCF formats to https://github.com/mcmero/SVclone#snv-input-formats. Feel free to post any error messages you're getting from your filtered mutect calls if these options don't suit (a sample of the VCF file would be helpful as well).

Cheers,
Marek

**Comment by willhooper** [comment]
Thanks Marek. After some tweaking of my VCFs I was able to get the mutect format working.
