### ISSUE TITLE
CCFs > 1

### ISSUE THREAD

**Issue by willhooper** [mcmero/SVclone#14]
This may be a naive question, but what is the interpretation of a CCF greater than 1?

**Comment by mcmero** [comment]
While in theory a CCF > 1 is not possible, adjustment due to purity and copy-number may produce variant (and/or cluster) CCFs that are greater than 1. This represents either uncertainty/variance around the mean of a CCF = 1 clonal cluster, or it could indicate that the purity/ploidy estimate is wrong. For example, if you're seeing strong evidence for a cluster at 1.5 CCF, it would be a good idea to double check your purity/ploidy fit from your copy-number caller.

**Comment by willhooper** [comment]
> represents either uncertainty/variance around the mean of a CCF = 1 clonal cluster

Ah okay, that makes sense. Just to confirm -- that's what's going on here, right?: 

![image](https://user-images.githubusercontent.com/16417350/96879422-07725180-144a-11eb-85f9-7e52548a4952.png)

**Comment by mcmero** [comment]
Ccube caps the cluster CCF at 1, so if your 'true' CCF is higher (relative to your purity), this will not be apparent in the cluster means. From your results, it is difficult to say if that is the result of variance or underestimated purity, as there is a small peak ~1.25 CCF, but interpretation would also depend on your sample and sequencing characteristics. I would return to your copy-number caller's purity estimate and check the purity fit.

One other thing you could try is ccube's own purity estimate. To run this, open your `<sample>_ccube_snv_results.RData` file in R, then run the following:

```
library(ccube)
GetPurity(data.frame(snvRes$ssm))
```

This will give you an independent purity estimate (details in [ccube preprint](https://www.biorxiv.org/content/10.1101/484402v1.abstract)).

**Comment by willhooper** [comment]
Sure, I see what you're saying. Assuming I have a 2x150bp sample with a copy number profile and purity estimate that I'm confident in, how would you treat variants with CCFs > 1 (ostensibly due to variance)? 

![image](https://user-images.githubusercontent.com/16417350/97463611-502c7d80-1916-11eb-866f-0ed1254f15e9.png)

**Comment by mcmero** [comment]
I would consider these as clonal variants. In most cases, it would be reasonable to set any variant with CCF > 1 to CCF = 1.
