### ISSUE TITLE
FFPE vs Frozen

### ISSUE THREAD

**Issue by mkinnaman** [mcmero/SVclone#15]
Marek,

Do you have any insight into picking up subclonal SV's with FFPE samples. I have some noisy FFPE samples that I have run through SVclone and the SV's that are found are almost always all clonal. Frozen samples I see a much cleaner distribution. I know this is likely intuitive given what is known about the quality of FFPE WGS but was curious to your thoughts.

Thanks,
Michael

**Comment by mcmero** [comment]
Hi Michael,

There's a little analysis on this in my [thesis](https://minerva-access.unimelb.edu.au/handle/11343/215901), particularly figures 31 and 42, where I looked at VAF and CCF correlation between FFPE and FF samples. The tissues weren't perfectly matched, and the depth of sequencing and purity were all low, but it looked like the correlation between them was pretty good. This was a very small sample set though, so it's hard to generalise.

Your sample purity, depth, number of SVs, as well as the FFPE sample preparation will determine a lot. Importantly, if your SV calls are high confidence (and SVclone's filtering pipeline should also help with that), and your copy-number profiles look good, then this is also a major factor in a good analysis. Check the clonal profile of your SCNAs and SNVs of your FFPE samples, to see whether they correspond to what you're seeing in your samples. In general though, I agree that it would make sense to have a cleaner VAF/CCF distribution profile for fresh frozen SVs.

Hope that helps.

Cheers,
Marek

**Comment by mkinnaman** [comment]
I know I posted this a while ago - but thought it might be interesting to share the ccf distributions of ffpe vs frozen samples:

FFPE:
![Screen Shot 2021-12-08 at 3 01 08 PM](https://user-images.githubusercontent.com/54551567/145276611-e0491337-bafc-4348-8040-93aa211ad9d7.png)

Frozen
![Screen Shot 2021-12-08 at 3 01 49 PM](https://user-images.githubusercontent.com/54551567/145276628-8de7bb6f-030c-4f47-90ec-ba8712f370ce.png)

It seems like for some reason the FFPE CCF's skew higher and wider and as a result - there are very few FFPE subclonal SV's identified using a cutoff of 0.7 - curious if you had any additional insights on this.

**Comment by mcmero** [comment]
I would check the purity estimates of your FFPE samples. CCFs skewed higher could indicate that purity may have been under-estimated. I'd also check the copy-number profile of the tumours to make sure they're not overly fragmented.
