### ISSUE TITLE
Determinism

### ISSUE THREAD

**Issue by willhooper** [mcmero/SVclone#17]
Hi, 

Quick question -- is the output of SVclone deterministic when not using the `--subsample` option?

Thanks,
Will

**Comment by mcmero** [comment]
There's no randomness in the read counting portion of the pipeline. The clustering should also be deterministic by I will let @keyuan confirm this.

**Comment by keyuan** [comment]
@willhooper There could be uncertainties due to local optimums of the variational fit. Normally, the uncertainty is very low when you use multiple repeats.

**Comment by willhooper** [comment]
Great, thank you both for your help! Much appreciated.
