### ISSUE TITLE
CRAM files

### ISSUE THREAD

**Issue by azhark2** [mcmero/SVclone#19]
Hi,

Is there support for CRAM files?

Thanks,
Azhar

**Comment by mcmero** [comment]
Currently, SVclone doesn't support CRAM files. But it looks like `pysam` (which is used by SVclone to handle BAMs) has support, so this should be easy to add. I'll look into it.

**Comment by mcmero** [comment]
I've tested a CRAM file, and it's working fine without any modifications to the code.
