### ISSUE TITLE
newer pysam versions break count.py

### ISSUE THREAD

**Issue by wresch** [mcmero/SVclone#2]
I believe this commit that is part of newer versions of pysam

https://github.com/pysam-developers/pysam/commit/11b373ae850c97880237879d9d42d77692f584c3

breaks https://github.com/mcmero/SVclone/blob/88ad382665f75999dac62a40e1e4d6c9ae231ecc/SVclone/SVprocess/count.py#L157

I think that line should be 

```
loc = '%s:%d-%d' % (bp['chrom'], max(0,bp['start']), bp['end'])
```

else, count.py will complain that

```
Fetching reads failed for loc: ...
```

**Comment by mcmero** [comment]
Thank you for pointing this out and sorry for the late response. The latest commit, `894318d`, fixes this issue.
