### ISSUE TITLE
cluster output snv_results.RData not being generated

### ISSUE THREAD

**Issue by Ignatiocalvin** [mcmero/SVclone#20]
Hi,

I've ran the cluster function and it managed to generate sv_results.RData and all the other related outputs but the snv results were nowhere to be found.  This is the error msg when running cluster: 
![image](https://user-images.githubusercontent.com/50834160/130952923-18ee045a-cdbf-4c1c-8ec7-7c8ca55a1fe2.png)

I found that the RunCcubePipeline() of snvRes on line 99 of cluster_with_ccube.R didn't execute properly. 
This is a part of the ccube_snv_input.txt that's being used:
![image](https://user-images.githubusercontent.com/50834160/130953295-7407ab90-db47-4a54-9211-a856a7c2ae20.png)

I read the issue board and there was a similar problem, leading to a fix in the filter command. I tried filtering again but it still couldn't produce the snv rdata. 
I would really appreciate your help and time.

Thanks.

**Comment by mcmero** [comment]
Can you please upload your `ccube_snv_input.txt` in text format? I'll see if I can recreate the error.

**Comment by Ignatiocalvin** [comment]
Thanks for your reply and help.
[data_ccube_snv_input.txt](https://github.com/mcmero/SVclone/files/7100937/data_ccube_snv_input.txt)

**Comment by mcmero** [comment]
I tried your input file, but couldn't reproduce the error. I would try a fresh install/update of ccube (https://github.com/keyuan/ccube).

**Comment by mcmero** [comment]
I encountered this bug running a different data set, and found that it was due to multiple mutations at the same SNV locus. (The file above ran fine because the mutation IDs were changed.) This is fixed in `1a8a36b`.

**Comment by Ignatiocalvin** [comment]
It works now, thank you for your help!
