### ISSUE TITLE
No Configuration File Found

### ISSUE THREAD

**Issue by kbredemeyer** [mcmero/SVclone#21]
Hello,
I recently installed svclone into its own environment using conda as suggested. 
Upon attempting to run svclone annotate I get the following error indicating a lack of configuration file:

_$ svclone annotate -i SV.vcf -b dedup.bam -s r1-annotate
Traceback (most recent call last):
  File "/miniconda3/envs/svclone/bin/svclone", line 10, in <module>
    sys.exit(main())
  File "/miniconda3/envs/svclone/lib/python3.6/site-packages/SVclone/cli.py", line 187, in main
    args.func(args)
  File "/miniconda3/envs/svclone/lib/python3.6/site-packages/SVclone/SVprocess/annotate.py", line 510, in preproc_svs
    raise ValueError('No configuration file found')
ValueError: No configuration file found_

Did I miss something during the setup process describing how to generate this file?
Thanks,
Kevin

**Comment by mcmero** [comment]
The config file needs to be specified by `-cfg <config_file>` or, by default, SVclone will check the current directory for an `svclone_config.ini` file. Please download the default config file like so:

```
wget https://raw.githubusercontent.com/mcmero/SVclone/master/svclone_config.ini
```

Make sure to check that the settings are appropriate for your sample.

I've now added this information to the README.
