### ISSUE TITLE
SVclone annotate skipping SV events

### ISSUE THREAD

**Issue by kbredemeyer** [mcmero/SVclone#22]
Hi Marek,
I've been having some trouble getting SVclone to run on some Manta vcfs and keep getting a string of the following errors.

Initially:
SV MantaBND:4:163646:163651:0:1:0:1 improperly paired or missing attributes

And later in the run:
Warning: record GWNJ-1012:554:GW2106121243rd:4:2161:9390:8015 contains invalid attributes, skipping

This is after manually changing bam associated parameters in the config.ini file as other issues have suggested.
I still get an output in simplified format where reciprocal translocations are merged, but all DEL and DUPs are missing. 
Maybe I just missed something in the documentation?
Wondering what might be causing these skipped SVs.
Thanks,
Kevin

**Comment by mcmero** [comment]
We haven't tested SVclone with Manta's SVs. Looking at the VCF output format, the deletion/duplication format is incompatible with SVclone's interpretation. I can look into adding this in the future, but for the moment you may have to make a script to process Manta's VCF data into SVclone's simple SV input format.
