### ISSUE TITLE
CNV input is breaking svclone filter

### ISSUE THREAD

**Issue by anoronh4** [mcmero/SVclone#25]
I have gotten SVclone to run, but recently decided to add CNV, and it broke the workflow. Here is my error:
```
Traceback (most recent call last):
  File "/opt/conda/envs/svclone/bin/svclone", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/envs/svclone/lib/python3.6/site-packages/SVclone/cli.py", line 187, in main
    args.func(args)
  File "/opt/conda/envs/svclone/lib/python3.6/site-packages/SVclone/run_filter.py", line 636, in run
    raise ValueError('No variants found to output!')
ValueError: No variants found to output!
```
and the output for `svclone filter` is as follows:
```
Running svclone filter
Filtered out 0 SNVs based on minimum depth
Filtered out 0 duplicated SNVs
Filtered out 5 SVs based on size limits
Filtered out 0 SVs based on minimum depth limit
Filtered out 3 SVs based on spanning/split read limits
Matching copy-numbers for SVs...
Filtered out 46 SVs with missing or invalid copy-numbers
Matching copy-numbers for SNVs...
Filtered out 3272 SNVs with missing or invalid copy-numbers

```
I checked and found that there were no chromosome mismatches between my copy number file and any of my other inputs (no `chr` prefix anywhere). The beginning of my copy number file, which was reformatted to resemble ASCAT, looks like this:
```
$ head -5 copynumber.csv
1,1,13116,249239550,2,1,2,1
2,2,10596,243188400,2,1,2,1
3,3,60560,28519350,2,1,2,1
4,3,28520335,29924817,2,1,1,0
5,3,29925100,69860350,2,1,2,1
```
I can't see what the problem is here. I am using `SVclone-1.0.2`.

**Comment by mcmero** [comment]
Can you show me a sample of your svinfo file?

**Comment by anoronh4** [comment]
Sure, see attached!
[DO52520_tumor__DO52520_normal_svinfo.txt](https://github.com/mcmero/SVclone/files/9580218/DO52520_tumor__DO52520_normal_svinfo.txt)

**Comment by mcmero** [comment]
Thanks for raising. This looks like a bug; I've fixed it in 4a02d5.

**Comment by sainadfensi** [comment]
Hi Marek,

Thanks for making and maintaining this tool. I've encountered the same issue although using the version 1.1.2

`svclone filter -s $sample -i Output/16004/test.txt \
 -p Input/${sample}/$sample.purity_ploidy  \
 -cfg $config -o Output/$sample -c $cnv`


All SVs are filtered out  `with missing or invalid copy-numbers
Traceback (most recent call last):
  File "/scratch/RDS-FMH-PopPCaGenomics-RW/Jue/Tools/SVclone/sv_clone-env/bin/svclone", line 8, in <module>
    sys.exit(main())
  File "/scratch/RDS-FMH-PopPCaGenomics-RW/Jue/Tools/SVclone/sv_clone-env/lib/python3.6/site-packages/SVclone/cli.py", line 187, in main
    args.func(args)
  File "/scratch/RDS-FMH-PopPCaGenomics-RW/Jue/Tools/SVclone/sv_clone-env/lib/python3.6/site-packages/SVclone/run_filter.py", line 636, in run
    raise ValueError('No variants found to output!')`

Likewise, I also reformatted CNV to resemble ASCAT, but I don't have ploidy information so I made 2 for most them. So I'm not sure if it is my input cause the issue:
`1,1,903175,2468175,2,2,4,2
2,1,2480012,2579949,3,3,6,2
3,1,2581666,2877584,2,2,4,1
4,1,2912986,3752637,3,2,5,0
5,1,3760208,4489342,2,2,4,2
`

The svinfo input: 

[test.txt](https://github.com/mcmero/SVclone/files/11494793/test.txt)

**Comment by mcmero** [comment]
Make sure your chromosome formats are the same for your CNV and SV input (e.g., chr1 or 1) and give it another try. By the way, your test inputs don't have any overlaps between your breakpoints and CNV regions.

**Comment by sainadfensi** [comment]
Thank you! it works after adding "chr" to CNV input.
