### ISSUE TITLE
SVclone bioconda installation error

### ISSUE THREAD

**Issue by kim1339** [mcmero/SVclone#28]
Hi there,

I was trying to install svclone, but am running into a non-descriptive error (screenshot attached). I've tried updating my conda installation, and installing both in and out of a virtual environment, but still get the error.

Any guidance would be appreciated, thank you!

![error_screenshot](https://user-images.githubusercontent.com/40971424/221961158-3de46bdc-b496-490a-8555-e2f6b7f35a25.PNG)

**Comment by mcmero** [comment]
I notice you are using Windows, which we haven't tested SVclone on, and therefore can't guarantee compatibility. Please try installing it using something like [Windows Subsystem for Linux](https://ubuntu.com/wsl).

**Comment by kim1339** [comment]
Thanks for your response! I had also already tried running the commands in a Linux environment, but recieved a Network error (screenshot attached).

![image](https://user-images.githubusercontent.com/40971424/223236711-f87706c7-ed34-4c97-a1ec-b6d852e4bcde.png)
