### ISSUE TITLE
Fetching reads failed 

### ISSUE THREAD

**Issue by 5utr** [mcmero/SVclone#3]
When I run annotate on the example data I get the following error for all the positions:

`-bash-4.2$ python SVclone.py annotate -i example_data/tumour_p80_DEL_svs_simple.txt -b example_data/tumour_p80_DEL_sv_extract_sorted.bam -s example_data --sv_format simple -cfg svclone_test.ini
Loading SV calls...
Inferring SV directions...
Fetching reads failed for loc: 12:227531:227555
Fetching reads failed for loc: 12:228238:228262
Fetching reads failed for loc: 12:333577:333601
Fetching reads failed for loc: 12:338286:338310
Fetching reads failed for loc: 12:461130:461154
Fetching reads failed for loc: 12:465976:466000
........`

**Comment by mcmero** [comment]
Sorry for the late reply. This is likely caused by newer versions of pysam breaking SVclone's fetching of reads from bam files. This has now been fixed.
