### ISSUE TITLE
svclone count --> ValueError: multiple tag sizes BAM file

### ISSUE THREAD

**Issue by handoko12u** [mcmero/SVclone#32]
Dear @mcmero 
I have a WGS human cancer data. I did SV call with Sniffles2, then annotate it with SnpEff.
I want to know the CCF, I want to do it with SVClone.
I suppose, I do not need to do the annotate step anymore, since my VCF file has been annotated with SnpEff, is that correct?

I continue to do svclone count, but there is an error, as shown below:
![image](https://github.com/mcmero/SVclone/assets/153805498/4db14643-688b-4ecf-aa46-f823c7899e2c)

Please help how to solve?
Thank you

**Comment by mcmero** [comment]
The count step does not support VCF input, so you will have to run the annotate step first. However, the error message indicates that you have different read lengths in your BAM, which SVclone does not support. If you do have a good idea of your average read size however, you can specify this in your config file to avoid this error.

**Comment by handoko12u** [comment]
Hello @mcmero 

I have set the average read and standard deviation in config file as follow:
# SV processing-related options

[BamParameters]
# read length of BAM file; -1 = infer dynamically.
read_len: -1

# Mean fragment length (also known as insert length); -1 = infer dynamically.
insert_mean: 2500

# Standard deviation of insert length; -1 = infer dynamically.
insert_std: 10000

# mean coverage of the bam
# used as parameter in cluster number initialisation
# informs max read depth we consider when extracting reads from SV loci
mean_cov: 50

# maximum considered copy-number
# informs max read depth we consider when extracting reads from SV loci
max_cn: 10

Then I try to run svclone annote, this is the result:

(svclone) sysadmin@sysadmin:/var/lib/minknow/data/20230907_LSK114_KNF_DNA_Long/4562949_ReRun1$ svclone annotate -i /home/sysadmin/Downloads/R_practice/sv_vcf/s1_phased.vcf -b /var/lib/minknow/data/20230907_LSK114_KNF_DNA_Long/4562949_ReRun1/bam_final/merged_sort.bam -s s1_annotate_svclone -cfg /home/sysadmin/Downloads/svclone_config.ini 
Loading SV calls...
Traceback (most recent call last):
  File "/home/sysadmin/mambaforge/envs/svclone/bin/svclone", line 10, in <module>
    sys.exit(main())
  File "/home/sysadmin/mambaforge/envs/svclone/lib/python3.10/site-packages/SVclone/cli.py", line 187, in main
    args.func(args)
  File "/home/sysadmin/mambaforge/envs/svclone/lib/python3.10/site-packages/SVclone/SVprocess/annotate.py", line 541, in preproc_svs
    svs = svp_load_data.load_input_vcf(svin, class_field, use_dir)
  File "/home/sysadmin/mambaforge/envs/svclone/lib/python3.10/site-packages/SVclone/SVprocess/svp_load_data.py", line 20, in load_input_vcf
    for sv in sv_vcf:
  File "/home/sysadmin/mambaforge/envs/svclone/lib/python3.10/site-packages/vcf/parser.py", line 586, in __next__
    samples = self._parse_samples(row[9:], fmt, record)
  File "/home/sysadmin/mambaforge/envs/svclone/lib/python3.10/site-packages/vcf/parser.py", line 485, in _parse_samples
    sampdat[i] = float(vals)

Please advice, what's wrong. Thanks

**Comment by mcmero** [comment]
SVclone's input format follows the [VCF specification for SVs](https://samtools.github.io/hts-specs/VCFv4.2.pdf), so it is possible your SV VCF does not follow this format. It would help if you posted a sample of your VCF input file. You could also try converting your SVs into the tab-delimited format described in the [README](https://github.com/mcmero/SVclone?tab=readme-ov-file#annotate-step).

**Comment by handoko12u** [comment]
here is my sample VCF file:
![image](https://github.com/mcmero/SVclone/assets/153805498/293b5b81-4557-4ccb-897b-a9a5eb66d35a)

**Comment by mcmero** [comment]
These look like SNV calls (not SVs). This VCF will not work as SV input, but you can still run SNVs through the pipeline from the filter step onwards, or run standalone [ccube](https://github.com/keyuan/ccube).

**Comment by handoko12u** [comment]
Ok will try ccube.

How about this VCF:
![image](https://github.com/mcmero/SVclone/assets/153805498/650d1366-9f8f-4356-ac40-e8c082c0260c)
is it SV VCF file?
Thanks

**Comment by mcmero** [comment]
Yes, that looks like an SV VCF.
