### ISSUE TITLE
VAF adjustment for duplications

### ISSUE THREAD

**Issue by surajraj99** [mcmero/SVclone#33]
I had a question on VAF adjustment for duplications. I think it makes sense for heterozygous variants where the real VAF is supposed to be 0.5. Let's say ploidy is 2, and tumor purity is 1.

In a real 0.5 VAF case, let's say the real support and normal counts are 10 and 20 respectively. The normal counts would be multiplied by 0.5 (which is 1 - (1/2), based on the eqn given in the paper) and the adjusted support and normal would become 10 and 10 respectively. This would give a VAF of 0.5.

But if it deviates from 0.5, say a subclonal variant of 0.2. The support and normal counted could be 4 and 20 respectively. The normal counts are multiplied again by 0.5, to give 4 and 10. This gives a VAF of 0.28.

Same with a homozygous duplication. The support and normal counted could be 20 and 20 respectively. The normal counts are multiplied again by 0.5, to give 20 and 10. This gives a VAF of 0.66, instead of 1.0.

This is what I observe with the data I provide too, the variants seem to center around 0.5. Am I understanding this wrong, and is there a way I can recapitulate expected VAFs?

**Comment by mcmero** [comment]
The normal counts refers to reads unaffected by the variant only, but the VAF is calculated over the total reads (support + normal). There's some more detail about this in section 2.3.2 of my [thesis](https://minerva-access.unimelb.edu.au/items/b97aa035-675c-5c76-8f97-7ed3dcaf3e8d).

**Comment by surajraj99** [comment]
I just read through the section you pointed out as well as a previous section but I am still a bit confused. Given the examples in my first post (I edited the subclonal final VAF, as as it was calculated wrong), the final VAF is different from the expected VAF for all the cases, save for the case where the true VAF is 0.5.

For example, in the homozygous example, the final VAF is 20 support / (20 support + 10 normal) = 0.66, not 1

**Comment by mcmero** [comment]
You are correct in that the VAF adjustment calculation assumes that the variant is heterozygous, this is an over-simplification, but it is by design. This is because at this point of the pipeline, we do not know the multiplicity (i.e, we don't know if the variant is homozygous or heterozygous). The multiplicity model in ccube then adjusts for this possibility. The VAF adjustment is just a heuristic to bring amplification normal read counts in line with other variants.
