### ISSUE TITLE
Error while running SV clone using the 'consensus' mode for SNVs

### ISSUE THREAD

**Issue by poojachandra** [mcmero/SVclone#35]
I want to input SNVs from multiple tools and would like to use SV Clone (with SNV) using the 'consensus' mode. 
The tool does not output the required output files. Is there an example of the file that I could use with the 'consensus' mode ?
Thanks

**Comment by poojachandra** [comment]
Thanks. What should be the format for consensus file ?

**Comment by mcmero** [comment]
Please see the [documentation](https://github.com/mcmero/SVclone?tab=readme-ov-file#snv-input-formats) for the supported SNV VCF formats.

**Comment by poojachandra** [comment]
Hi, 
Based on the documentation and using this file https://dcc.icgc.org/api/v1/download?fn=/release_28/Projects/BRCA-EU/simple_somatic_mutation.open.BRCA-EU.tsv.gz as an example, I created a file with the following columns to the consensus file:

- chromosome
- chromosome_start
- chromosome_end
- chromosome_strand
- assembly_version
- mutation_type
- reference_genome_allele
- mutated_from_allele
- mutated_to_allele
- total_read_count
- mutated_allele_read_count

But, the SV Clone is not taking the SNV input. 
Is there a column that might be missing ?
Or perhaps if you could point me to an example file (with open access) for the consensus approach that would be helpful.

Thank You

**Comment by mcmero** [comment]
Can you please post the command and error message from SVclone, as well as a sample of your VCF input? The consensus format has t_ref_count and t_alt_count fields in the INFO field. I don't have a sample on hand as these data are behind ICGC access control.

There is nothing 'special' about this format specifically for consensus calls, it was just what was used in the PCAWG project by the variant calling working group. Any of the supported SNV formats will work when you create your SNV file, it will just depend on the VCF output you have available from your variant callers.

**Comment by poojachandra** [comment]
Here are the commands:

svclone annotate -i SV_input -b Bam -s sampleID --sv_format simple -cfg svclone_config.ini
svclone count -i sampleID/sampleID_svin.txt -b Bam -s sampleID
svclone filter -s sampleID -i sampleID/sampleID_svinfo.txt -p Purity_Ploidy_input.txt  --cnvs CNV_input.csv --snvs test_snv.txt --snv_format consensus

Attaching the input snv file as well.
[test_snv.txt](https://github.com/user-attachments/files/15812861/test_snv.txt)

**Comment by mcmero** [comment]
Your SNV input is not in VCF format. Please see [here](https://samtools.github.io/hts-specs/VCFv4.2.pdf) for the VCF file format specification. An example [vcf file](https://github.com/mcmero/SVclone/blob/master/example_data/tumour_p80_DEL_snvs.vcf) is provided in the SVclone repository (this uses the mutect format).
