### ISSUE TITLE
'snv_results.RData' file not being generated

### ISSUE THREAD

**Issue by poojachandra** [mcmero/SVclone#36]
Hi, 
I am able to generate all the outputs except the 'snv_results.RData' file at the 'svclone cluster' step.
The pipeline does not throw any errors and 'ccube' is installed as well.

Is there anything else I might be missing ?

Thank You

**Comment by mcmero** [comment]
Can you try (within your output directory):

```bash
find . -iname "*.RData"
```

The snv_results.RData file should be under the `sample/ccube_out/snvs` subdirectory. If it isn't there, is the RData file for SVs present? Is the snvs RData file being generated for the example data run with `run_example_wsnvs.sh`?
