### ISSUE TITLE
Output file for SV VAF

### ISSUE THREAD

**Issue by poojachandra** [mcmero/SVclone#37]
Hi,

I am looking for SV VAF and would like to confirm which file I should reference.
Is it the 'ccube_sv_input.txt' file; with columns 'vaf1 and 'vaf2' ?
Thank You

**Comment by mcmero** [comment]
The vaf1/vaf2 values are the same as the adjusted_vaf1/2 found in the [filter output](https://github.com/mcmero/SVclone?tab=readme-ov-file#filter-output). These adjusted support/norm values are the ones used by ccube for clustering. The filter output also contains the mean VAF per SV and the [count output](https://github.com/mcmero/SVclone?tab=readme-ov-file#count-output) contains the raw VAFs.

**Comment by poojachandra** [comment]
Thanks for the clarification @mcmero
Also, could you please confirm the file having CCF as well ?

**Comment by mcmero** [comment]
The `ccube_sv_input.txt` file does not contain CCFs, it is the input to the clustering algorithm that infers CCF (as well as clusters, multiplicity etc.). Please see the [cluster output documentation](https://github.com/mcmero/SVclone?tab=readme-ov-file#cluster-output).

**Comment by poojachandra** [comment]
Thanks. 
I am looking at the link above, and the link mentions '<sample>_subclonal_structure: clusters found, the number of variants per cluster, the proportion and CCF.'  but in my 'subclonal_structure.txt' file, I have only three columns: cluster, n_ssms and proportion.
Is there something that I might be missing ?

**Comment by mcmero** [comment]
You are right, the `subclonal_structure.txt` file only contains the proportion and not the CCF (fixed in cb4659f). This file contains the cluster level information you are looking for (SVs per cluster). You can calculate the CCF by dividing the proportion by the tumour purity.
