### ISSUE TITLE
Compatibility to long-read data

### ISSUE THREAD

**Issue by ywzhang071394** [mcmero/SVclone#38]
Hi,
Thank you for the nice tool.
We recently tried to identify the subclonal SVs using SVclone. However, our data is long-read WGS and we got incorrect read counts from SVclone (i.e. VAF is equal to 1). Is SVclone compatible to Pacbio BAM file?

**Comment by mcmero** [comment]
SVclone is not compatible with long-read data, and would require a fundamental reworking of the counting step to support long-reads. It would only be possible (in theory) to use SVclone from the filter step and would require some data wrangling to get this to work. 

If you wanted to do this, I would suggest calling your SVs using something like [sniffles](https://github.com/fritzsedlazeck/Sniffles), which will output support and total coverage read counts for each SV break-end. At this point, you could parse the VCF output and convert it to SVclone's [count format](https://github.com/mcmero/SVclone?tab=readme-ov-file#count-output) and feed it into SVclone's filter step.

You would have to create dummy values for some of the fields. For example, there will be no 'spanning' reads for long-read data, so use only the split read categories and make sure you set `min_span: 0` in the config. You could probably ignore/create dummy values for the `anomalous` and `sc_bases` fields.

**Comment by ywzhang071394** [comment]
Thank you for the information. We actually have both long read and short read WGS. 
Our strategy has been changed to run SVclone using long-read SVs and short-read bam file. 
We have 60+ somatic SVs and ~40x bam file. However, the SVclone count has run >12h. 
What is the regular time of this process? I just want to confirm my setting is fine. 




I do not know how you set up the bam parameters. To me, "-1" never works well. Therefore, I manually set several values according to the illumina library construction.


# SV processing-related options
[BamParameters]
# read length of BAM file; -1 = infer dynamically.
read_len: 150

# Mean fragment length (also known as insert length); -1 = infer dynamically.
insert_mean: 350

# Standard deviation of insert length; -1 = infer dynamically.
insert_std: -1

**Comment by mcmero** [comment]
That sounds like a long time for the count step to run on such a small number of SVs. Check the inferred `insert_std` in your `read_params.txt` file. If this is too large it will cause issues, in which case try setting it manually.

**Comment by ywzhang071394** [comment]
Could you give some clues for the potential **insert_std** value?
i.e., what are the typical **insert_std** values in most Illumina WGS data? or how can I obtain this value?

**Comment by ywzhang071394** [comment]
solved, Thanks!
