### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by ywzhang071394** [mcmero/SVclone#39]
Hi,
Thank you for the nice tool!
We recently tested SVclone on our bwa-generated bam files but it reported some warnings:
_**"Warning: record LH00195:128:227GTYLT4:7:1440:26919:9699:GGTAATTTA contains invalid attributes, skipping"...**_

my parameters are:

```
[BamParameters]
# read length of BAM file; -1 = infer dynamically.
read_len: 150

# Mean fragment length (also known as insert length); -1 = infer dynamically.
insert_mean: 300

# Standard deviation of insert length; -1 = infer dynamically.
insert_std: 30
```

The read in bam file is:
```
LH00195:128:227GTYLT4:7:1440:26919:9699:GGTAATTTA	121	chr6	171421839	0	95S56M	=	171421839	0	CACCCCATTACTCCATCCATCCCCATCCCTCCATCCATCCCATTCCGTTAGATGGCCTCGTTCCTCCATTTGTCTCGTTCGGCCGTGCATTTCTGTCCTTCCGTCCACCCTATCCCTCCATCCACCCCATCCCTCCATCCACCCCATCCCT	9--9999--9999-9I-9-9---99-I999--99--99-99-9I9-9-9-9-9--99-9-----9---99------9--9I-----9--I--9-99---99---99-9II-II9II99IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	SA:Z:chr6,171423036,-,46M105S,0,1;	MD:Z:7A7C40	PG:Z:MarkDuplicates	RG:Z:HT870N1-S1H1A3Y1de1.T	NM:i:2	AS:i:46	XS:i:43
LH00195:128:227GTYLT4:7:1440:26919:9699:GGTAATTTA	181	chr6	171421839	0	*	=	171421839	0	GGCTGGGTGGGGGGGGGGGGGGGGGGGAGGAGGGGGATGGAT	II--I---9--9I----II-II---I--II---IIIIIIIII	MC:Z:95S56M	PG:Z:MarkDuplicates	RG:Z:HT870N1-S1H1A3Y1de1.T	AS:i:0	XS:i:0
LH00195:128:227GTYLT4:7:1440:26919:9699:GGTAATTTA	377	chr6	171423036	0	46M105H	=	171423036	0	CACCCCATTACTCCATCCATCCCCATCCCTCCATCCATCCCATTCC	9--9999--9999-9I-9-9---99-I999--99--99-99-9I9-	SA:Z:chr6,171421839,-,95S56M,0,2;	XA:Z:chr6,-171422881,43M108S,1;chr6,-171423295,37M114S,0;	MD:Z:37C8	PG:Z:MarkDuplicates	RG:Z:HT870N1-S1H1A3Y1de1.T	NM:i:1	AS:i:41	XS:i:38
```

We have no idea about this warning, could you give some suggestions? Thank you!

**Comment by ywzhang071394** [comment]
Also, for SV classification, there is no "Insertion" sepcific. 
Where should i add "insertion" to? "dna_gain_class" or "itrx_class"?

**Comment by Lokedout89** [comment]
review-requested:[USERNAME]

**Comment by mcmero** [comment]
Looks like you have some formatting issues in your bam file, your middle read record is missing a tab between `=171421839`. 

If the insertion sequence itself is in the reference and duplicated, use `dna_gain_class`, otherwise use `itrx_class`. SVclone doesn't support non-reference insertions.

**Comment by ywzhang071394** [comment]
Sorry, the missing tab was caused by an issue during the copy-paste process.
It is correct in the bam file. This bam file is originally generated by bwa, I have not done any modification.

**Comment by mcmero** [comment]
The middle read also does not have a CIGAR string (indicated by `*`), which means that SVclone cannot process it. It is normal to see this warning occasionally. We don't expect to be able to process every read perfectly.

**Comment by ywzhang071394** [comment]
Sure, Thank you for the help!
