### ISSUE TITLE
Information about calculating Population frequency or VAF using SVclone

### ISSUE THREAD

**Issue by poddarharsh15** [mcmero/SVclone#41]
Hi @mcmero,  

I hope you're doing well. I was wondering if it's possible to calculate the population frequency for variants present in my cohort (approximately 400 samples) to reduce the number of variants. Specifically, I'm interested in variants that are present in at least 10% of my cohort.

Do you think calculating Variant Allele Frequency (VAF) using `SVClone` would help with this task? For context, I am working with WES samples and used `DYSGU` to call variants. I now have a merged VCF file containing all the variants across my 400 samples.

I’d really appreciate any suggestions or insights on how to approach this!

Best regards,
Harsh.

**Comment by mcmero** [comment]
Are your samples individually sequenced? If they are pooled, it could work to use SVclone to calculate VAFs from the pooled bam files, as long as the depth isn't too high. You could assume neutral copy-numbers.

If your samples are individually sequenced, I'm not sure there's much to gain from using SVclone, unless you wanted to cluster groups of SVs together at similar frequency, in which case you could run them through SVclone/ccube's cluster step.

**Comment by poddarharsh15** [comment]
Hi @mcmero,

Thanks a lot for the clarification! I’m not entirely sure if the samples were sequenced individually since I’m working with data generated several years ago. 😔 However, each sample does have its own separate FASTQ files (WES data), and they were aligned separately to the GRCh38 reference genome to produce individual BAM files.

Thanks again!
