### ISSUE TITLE
interpretation of results / clustering with only 1 SV

### ISSUE THREAD

**Issue by Sames-Jtudd** [mcmero/SVclone#6]
Hi there, nice package! 
I just had a 2 quick questions.
1) in the cluster certainty file produced by the cluster step there are columns called average proportion(1/2). Could you elaborate of what the difference is between these two values and how they should best be resolved to a per SV CCF.

On the github page it states that this value (in the average proportion column) is the CCF*purity. Just wanted to clarify that this is correct. 
Unless mistaken the CCF (cancer cell fraction) * purity = cellular fraction. So if you want the CCF you would need to convert it back (divide by the purity).

2) In samples with only one SV passing filtering the clustering step is not fully performed and doesn't produce a cluster certainty file. While clustering of 1 SVs in nonsensical it is relevant to cluster then with SNVs, ( i have provided an SNV file for this command)  and also to produce an estimate of the CCF. 

Is it possible to either force the program to perform clustering or generate a CCF estimates in these cases. 

thanks 

Jamie

**Comment by mcmero** [comment]
Hi Jamie,

1. average_proportion(1/2) are calculated using VAF(1/2) of the SV respectively (left/right normal read counts). See 'Calculating variant CCFs' section in the paper methods for more details. You are correct with the CCF calculation: average_proportion/purity will give you the CCF. Taking the average of CCF1 and CCF2 should be adequate for an SV-level CCF in most cases. 

2. This is possible but currently not supported as ccube returns a slightly different format if you give it only one variant. I've made a note of this and will handle this case in a future release.

Cheers,
Marek

**Comment by Sames-Jtudd** [comment]
Thanks for the quick reply.

Best Jamie

**Comment by mcmero** [comment]
The latest commit now handles the case of running a single SV through the clustering step, which can be used with the post-assign functionality.

**Comment by Sames-Jtudd** [comment]
Sweet, cheers that was fast.

Best

Jamie

**Comment by wanhui5867** [comment]
Hi Marek,

I also encountered only 1 SV after filtering. Is it different from other results in that it does not produce a graph pdf file??

Additionally, how about the situation that only 1 SV as raw SV input? I tested that it will arise Error ` TypeError: iteration over a 0-d array` in the annotating step. I wonder if it is reasonable that let this situation also produce ccube results like the above situation?

**Comment by mcmero** [comment]
Thank you for raising this. I've just pushed a commit that deals with the situation of only 1 SV input at the annotate step. 

Regarding the output plot, unfortunately this is not produced for a single SV, as this requires ccube's clustering results object, which is not available for a single SV.

**Comment by wanhui5867** [comment]
Thanks for your quick reply! I tried it and it works now.
