### ISSUE TITLE
count function stalls out

### ISSUE THREAD

**Issue by mkinnaman** [mcmero/SVclone#7]
HI Team,

I have been having issues at the count step. It seems to stall out after going through one read without throwing an error - unclear where to start with troubleshooting.

Thanks,

Michael

**Comment by mcmero** [comment]
Hi Michael,

Could you please post the output from the command line up until the point where it stalls?

Thanks,
Marek

**Comment by mkinnaman** [comment]
Ok I have attached my input, annotate and what the results of count before it stalls out. There is no output from the command line - just from LSF stating the job was killed due to it timing out. It prints two lines in the svinfo before stalling out.


[erms_5_svin.txt](https://github.com/mcmero/SVclone/files/4456196/erms_5_svin.txt)
[erms_5_svinfo.txt](https://github.com/mcmero/SVclone/files/4456197/erms_5_svinfo.txt)
[erms5_simple.txt](https://github.com/mcmero/SVclone/files/4456203/erms5_simple.txt)

**Comment by mcmero** [comment]
From your output, it looks like SVclone is inferring directions, even though they are present in your 
erms5_simple.txt input file. Please set `use_dir: True` under `[SVannotateParameters]` in your config file and try running the annotate and count steps again, making sure you are using the same bam file for both steps.

**Comment by mkinnaman** [comment]
Hi Marek,

I have tried running with multiple inputs and still having issues at the count step. I confirmed use_dir was set to true and was using same bam for each step. I have used both simple and vcf input from gridds but run into the same issue at count step. This is the output before it fails:

`Insert mean of 205928.830168, with standard deviation of 6317256.667097 inferred
WARNING: anomalous insert sizes detected. Please 
              double check or consider setting values manually.
Extracting data from 503 SVs
Fetching reads failed for loc: 1:0-19982878
Fetching reads failed for loc: 1:0-20862771
Fetching reads failed for loc: 1:0-19982878
Fetching reads failed for loc: 1:0-20862771
skipping 1:1540702|1:2957159 (UNKNOWN_DIR)
Fetching reads failed for loc: 1:0-20706139
Warning: record A00227:48:H2WW3DSXX:4:2573:30734:6339 contains invalid attributes, skipping`

Thanks,
MIchael

**Comment by mcmero** [comment]
From your output, it looks like the insert size mean and standard deviation were not correctly estimated; this can happen for some bam files. You'll need to set the average fragment size and standard deviation for your sequencing data manually in your config file under `[BamParameters]`. Delete your `read_params.txt` file under your sample directory and then try running again from the annotate step.

**Comment by mkinnaman** [comment]
Thanks! That fixed that issue...

Now I am trying to run filter with snvs from mutect and copy number from battenberg - throwing an error not sure how to troubleshoot:

`./SVclone.py filter -s I-H-134255-T10-1-D1-1 -i /home/kinnamam/SVclone/I-H-134255-T10-1-D1-1/I-H-134255-T10-1-D1-1_svinfo.txt --snvs /work/isabl/data/analyses/47/52/164752/mutect/I-H-134255-T10-1-D1-1_vs_I-H-134255-N1-1-D1-1.snvs.vcf.gz --snv_format mutect -c /work/isabl/data/analyses/21/40/112140/I-H-134255-T10-1-D1-1_subclones.txt 
Filtered out 0 SNVs based on minimum depth
Filtered out 1 SVs based on size limits
Filtered out 132 SVs based on minimum depth limit
Filtered out 1 SVs based on spanning/split read limits
Matching copy-numbers for SVs...
Filtered out 10 SVs with missing or invalid copy-numbers
Filtered out 1 SVs where major or minor alleles exceed the CN max
Matching copy-numbers for SNVs...
Traceback (most recent call last):
  File "./SVclone.py", line 163, in <module>
    args.func(args)
  File "/home/kinnamam/SVclone/SVclone/run_filter.py", line 604, in run
    snv_df = match_snv_copy_numbers(snv_df,cnv_df)
  File "/home/kinnamam/SVclone/SVclone/run_filter.py", line 285, in match_snv_copy_numbers
    bp_chroms = sorted(bp_chroms, key=lambda item: (int(item) if item.isdigit() else str(item)))
TypeError: unorderable types: str() < int()
`

Let me know what you think - thanks for your help thus far

**Comment by mcmero** [comment]
No worries, glad that fixed the issue.

Thanks for raising the run_filter issue; this happens in some version of python. I've fixed this in the latest commit, so please try pulling the latest version and give it another try.

**Comment by mkinnaman** [comment]
Awesome - smooth sailing now from start to finish - thanks for all your help!
