### ISSUE TITLE
0 spanning read counts

### ISSUE THREAD

**Issue by trwo** [mcmero/SVclone#8]
Hello, 

I'm trying to use SVclone for a list of BRASS calls and the original BAM file. It generates counts and estimates plausible VAFs but the 'spanning' counts column remains empty for all SVs except one. I have visualised all these breakpoints myself in Jbrowse and confirmed they map to other genomic regions using UCSC blat so I'm not sure why it would fail to count them. Do you know of any reason why SVclone might be failing to flag these reads as spanning? It leaves me with a *filtered_svs.tsv file with a single SV rather than 61.

Thanks for your time.

**Comment by mcmero** [comment]
Please check the `read_params.txt` file under your output directory. If the fragment length and standard deviation don't look sensible, then this is the most likely cause of your issue and you'll have to manually set them. This can be done by setting these values in the config file under `[BamParameters]`. Delete the `read_params.txt` file and try rerunning from the annotate step.

**Comment by trwo** [comment]
Ah, OK thanks. I will be sure to manually set these.
